Ext.define("Ext.ux.ItemSelectorRv",{extend:"Ext.ux.form.ItemSelector",alias:["widget.itemselectorrvfield","widget.itemselectorrv"],alternateClassName:["Ext.ux.ItemSelectorRv"],createList:function(b){var a=this;return Ext.create("Ext.ux.form.MultiSelectSI",{submitValue:false,flex:1,title:b,store:{model:a.store.model,data:[]},displayField:a.displayField,listConfig:a.listConfig,disabled:a.disabled,listeners:{boundList:{scope:a,itemdblclick:a.onItemDblClick,drop:a.syncValue}}});
},onTopBtnClick:function(){var c=this.toField.boundList,a=c.getStore(),b=this.getSelections(c);a.suspendEvents();a.remove(b,true);a.insert(0,b);a.resumeEvents();c.refresh();this.syncValue();c.getSelectionModel().select(b);},onBottomBtnClick:function(){var c=this.toField.boundList,a=c.getStore(),b=this.getSelections(c);
a.suspendEvents();a.remove(b,true);a.add(b);a.resumeEvents();c.refresh();this.syncValue();c.getSelectionModel().select(b);},onUpBtnClick:function(){var f=this.toField.boundList,b=f.getStore(),e=this.getSelections(f),g,d=0,a=e.length,c=0;b.suspendEvents();for(;d<a;++d,c++){g=e[d];c=Math.max(c,b.indexOf(g)-1);
b.remove(g,true);b.insert(c,g);}b.resumeEvents();f.refresh();this.syncValue();f.getSelectionModel().select(e);},onDownBtnClick:function(){var e=this.toField.boundList,a=e.getStore(),d=this.getSelections(e),f,c=d.length-1,b=a.getCount()-1;a.suspendEvents();for(;c>-1;--c,b--){f=d[c];b=Math.min(b,a.indexOf(f)+1);
a.remove(f,true);a.insert(b,f);}a.resumeEvents();e.refresh();this.syncValue();e.getSelectionModel().select(d);},onAddBtnClick:function(){var g=this,f=g.getSelections(g.fromField.boundList);g.moveRec(true,f);g.toField.boundList.getSelectionModel().select(f);var a=Ext.getCmp("itemselectHostsForService");
if(a!=null&&a!="undefined"){var d="";var b="";var c=publicJSON["modify"];if(c=="false"){d=Ext.getCmp("aggcombo").isVisible();b=Ext.getCmp("aggcombo").getValue();}else{if(c=="true"){d=publicJSON["displayCheckBox"];var e=publicJSON["isAggregateSite"];if(e=="true"){b="Yes";}else{b="no";}}}if(d){if(b=="Yes"){servicePage("hide");
}}}},onRemoveBtnClick:function(){var g=this,f=g.getSelections(g.toField.boundList);g.moveRec(false,f);g.fromField.boundList.getSelectionModel().select(f);var a=Ext.getCmp("itemselectHostsForService");if(a!=null&&a!="undefined"){var d="";var b="";var c=publicJSON["modify"];if(c=="false"){d=Ext.getCmp("aggcombo").isVisible();
b=Ext.getCmp("aggcombo").getValue();}else{if(c=="true"){d=publicJSON["displayCheckBox"];var e=publicJSON["isAggregateSite"];if(e=="true"){b="Yes";}else{b="no";}}}if(d){if(b=="Yes"){servicePage("show");}}}},moveRec:function(f,e){var c=this,g=c.fromField,a=c.toField,b=f?g.store:a.store,d=f?a.store:g.store;
b.suspendEvents();d.suspendEvents();b.remove(e);d.add(e);b.resumeEvents();d.resumeEvents();g.boundList.refresh();a.boundList.refresh();c.syncValue();},syncValue:function(){var a=this;a.mixins.field.setValue.call(a,a.setupValue(a.toField.store.getRange()));},onItemDblClick:function(a,d){var c=this;if(a==c.toField.boundList){c.onRemoveBtnClick();
}else{if(a==c.fromField.boundList){var b=Ext.getCmp("itemselectHostsForSegment");if(b==null||b=="undefined"){c.onAddBtnClick();}}}},setValue:function(f){var d=this,g=d.fromField,a=d.toField,b=g.store,e=a.store,c;if(!d.fromStorePopulated){d.fromField.store.on({load:Ext.Function.bind(d.setValue,d,[f]),single:true});
return;}f=d.setupValue(f);d.mixins.field.setValue.call(d,f);c=d.getRecordsForValue(f);b.suspendEvents();e.suspendEvents();b.removeAll();e.removeAll();d.populateFromStore(d.store);Ext.Array.forEach(c,function(h){if(b.indexOf(h)>-1){b.remove(h);}e.add(h);});b.resumeEvents();e.resumeEvents();Ext.suspendLayouts();
g.boundList.refresh();a.boundList.refresh();Ext.resumeLayouts(true);}});function servicePage(r){var c=publicJSON["modify"];Ext.getCmp("mappingcombo").show(true);var h="";var e="";if(c=="true"){h=Ext.getCmp("servicecombo").getValue();}else{if(c=="false"){h=Ext.getCmp("servicename").getValue();}}var o=Ext.getCmp("sitecombo").getValue();
if(o=="Yes"){e="false";}else{if(o=="No"){e="true";}}var p=Ext.getCmp("zonecombo").getValue();if(p==null||p=="null"){p="-1";}var d="false";var k=Ext.getCmp("aggcombo").getValue();var v=Ext.getCmp("aggcombo").isVisible();if(k!=null&&v){if(k=="Yes"){d="true";}else{if(k=="No"){d="false";}}}var g=Ext.getCmp("segmentcombo").getValue();
var n=Ext.getCmp("itemselectHostsForService").getValue();var l=new Array();for(var u=0;u<Ext.getCmp("itemselectHostsForService").getStore().getCount();u++){var q=Ext.getCmp("itemselectHostsForService").getStore().getAt(u).get("valueField");var a=false;for(var t=0;t<n.length;t++){if(q==n[t]){a=true;break;
}}if(!a){l[l.length]=q;}}var f=l;var m=f.toString();var s=Ext.getCmp("hiddencontainer");var w={xtype:"hiddenfield",name:"currentRemovedElements",value:n};s.add(w);w={xtype:"hiddenfield",name:"service",value:e};s.add(w);w={xtype:"hiddenfield",name:"site",value:h};s.add(w);w={xtype:"hiddenfield",name:"zone",value:p};
s.add(w);w={xtype:"hiddenfield",name:"segment",value:g};s.add(w);w={xtype:"hiddenfield",name:"aggsiteassHosts",value:m};s.add(w);var b=Ext.getCmp("componentservice").getForm();b.submit({url:"Services/data/EgConfigSitesJson.jsp?modify="+c+"&isAggregateSite="+d+"&displaySiteMap=true",method:"POST",standardSubmit:false,success:function(i,x){var j=x.response.responseText;
publicJSON=Ext.decode(j);if(!Ext.isEmpty(j)&&x.response.status==200){var y=publicJSON["displaySiteMap"];if(y=="true"){Ext.getCmp("mappingcombo").getStore().loadRawData(publicJSON["aggregateSite"]);Ext.getCmp("mappingcombo").setValue(publicJSON["mappingSiteName"]);}else{Ext.getCmp("mappingcombo").hide();
}}s.removeAll();},failure:function(){s.removeAll();}});}